import { test, expect } from './fixtures'
import { analyzerResult, analyzerState, lexicalStatistics, manualParse, tokenAnalysisResult } from '../fixtures'

test('one Analyze action gives a verdict and moves every detailed result to Analysis', async ({ page, api }) => {
  const raw = '  Mbom\t\n'
  const result = analyzerResult({ text: raw })
  result.grammar.steps = [{
    operation: 'Left recursion elimination', before: { S: [['S', 'NOUN'], ['NOUN']] },
    after: { S: [['NOUN', 'S_tail']], S_tail: [['NOUN', 'S_tail'], []] },
    description: 'Synthetic deterministic transformation fixture.',
  }]
  result.grammar.warnings = ['Fixture warning: grammar coverage still needs observed data.']
  api.reply('POST', '/api/analyzer/analyze', result)
  await page.goto('/')
  await page.getByLabel('Statement to analyze').fill(raw)
  await page.getByText('Grammar settings', { exact: true }).click()
  await page.getByLabel('Context-free grammar').fill('S -> S NOUN | NOUN')
  await page.getByRole('button', { name: 'Analyze', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Parser result', exact: true })).toBeVisible()
  await expect(page.getByText('ACCEPT', { exact: true })).toBeVisible()
  await expect(page.getByRole('table')).toHaveCount(0)
  await expect(page.getByRole('heading', { name: 'Syntactic analysis', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'View detailed analysis' }).click()
  await expect(page).toHaveURL(/#analysis$/)
  await expect(page).toHaveTitle('Analysis — Mboa Compiler')
  await expect(page.getByRole('heading', { level: 1, name: 'Analysis' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Analyzed sentence', exact: true })).toBeVisible()
  expect(await page.getByLabel('Analyzed source text').textContent()).toBe(raw)
  await page.getByText('Parser trace for this sentence', { exact: true }).click()
  await expect(page.getByRole('region', { name: 'Table-driven parser step trace' })).toBeVisible()
  await page.getByText('Transformations, FIRST/FOLLOW & LL(1) table', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Computed grammar' })).toBeVisible()
  await expect(page.getByText('Fixture warning: grammar coverage still needs observed data.')).toBeVisible()
  await page.getByText('Left recursion elimination', { exact: false }).click()
  await expect(page.getByText('Synthetic deterministic transformation fixture.')).toBeVisible()
  await expect(page.getByRole('region', { name: 'Computed FIRST and FOLLOW sets' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'LL(1) predictive parsing table, scroll horizontally' })).toBeVisible()
  await page.getByText('Saved Collection - 0 records', { exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Saved-statement token analysis' })).toBeVisible()
  await expect(page.getByText('Token frequencies · 0 forms', { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Own-data acceptance tests' })).toBeVisible()
  expect(api.calls('/api/analyzer/analyze')).toHaveLength(1)
  expect(api.calls('/api/analyzer/analyze')[0]?.body).toEqual({ text: raw, grammar: 'S -> S NOUN | NOUN' })
  expect(api.calls('/api/analyzer/grammar')).toHaveLength(0)
  expect(api.calls('/api/dataset', 'POST')).toHaveLength(0)
  expect(api.calls('/api/coursework/parse')).toHaveLength(0)
  expect(api.calls('/api/analyze')).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)

  await page.getByRole('link', { name: 'Back to Franc Analyzer' }).click()
  await expect(page.getByLabel('Statement to analyze')).toHaveValue(raw)
  await page.getByText('Grammar settings', { exact: true }).click()
  await page.getByLabel('Context-free grammar').fill('S -> epsilon')
  await expect(page.getByRole('heading', { name: 'Parser result' })).toHaveCount(0)
  await page.getByLabel('Statement to analyze').fill('')
  const empty = analyzerResult({
    text: '', lexical: { tokens: [], code_mixed_spans: [], verb_phrases: [], slang_expressions: [], statistics: lexicalStatistics() }, parse: manualParse().parse,
  })
  empty.grammar = {
    ...empty.grammar, original: { S: [[]] }, transformed: { S: [[]] }, terminals: [],
    first: { S: ['epsilon'] }, table: { S: { $: [] } },
  }
  api.reply('POST', '/api/analyzer/analyze', empty)
  await page.getByRole('button', { name: 'Analyze', exact: true }).click()
  await expect(page.getByText('ACCEPT', { exact: true })).toBeVisible()
  expect(api.calls('/api/analyzer/analyze')[1]?.body).toEqual({ text: '', grammar: 'S -> epsilon' })
  await page.getByRole('link', { name: 'View detailed analysis' }).click()
  await expect(page.getByRole('region', { name: 'Analyzed sentence' }).getByText('0 tokens · 0 distinct forms', { exact: true })).toBeVisible()
  await expect(page.getByText('No lexical tokens. The parser will see only $.')).toBeVisible()
  await page.getByRole('link', { name: 'Back to Franc Analyzer' }).click()
  await page.getByLabel('Statement to analyze').fill('New input, not fieldwork.')
  await expect(page.getByRole('heading', { name: 'Parser result' })).toHaveCount(0)
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Analysis', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'No completed analysis' })).toBeVisible()
  expect(api.calls('/api/analyzer/analyze')).toHaveLength(2)
})

test('grammar saving is explicit and does not expose report or presentation generation', async ({ page, api }) => {
  const grammar = 'S -> VERB'
  api.on('PUT', '/api/analyzer/grammar', async (route, request) => {
    expect(request.body).toEqual({ grammar })
    api.analyzer = analyzerState(grammar)
    await route.fulfill({ json: { grammar } })
  })
  await page.goto('/')
  await page.getByText('Grammar settings', { exact: true }).click()
  await page.getByLabel('Context-free grammar').fill(grammar)
  await expect(page.getByText('Using unsaved grammar', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Save grammar', exact: true }).click()
  await expect(page.getByText('Using saved grammar', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save grammar', exact: true })).toBeDisabled()
  await page.reload()
  await page.getByText('Grammar settings', { exact: true }).click()
  await expect(page.getByLabel('Context-free grammar')).toHaveValue(grammar)
  await expect(page.getByRole('button', { name: /Download coursework|Save project|Upload screenshot/ })).toHaveCount(0)
  await expect(page.getByLabel(/Group member|Linguistic discussion/)).toHaveCount(0)
  expect(api.calls('/api/analyzer/grammar')).toHaveLength(1)
  expect(api.calls('/api/analyzer/analyze')).toHaveLength(0)
  expect(api.calls('/api/coursework/export')).toHaveLength(0)
})

test('combined analysis failures remain explicit and do not display a stale successful parse', async ({ page, api }) => {
  api.reply('POST', '/api/analyzer/analyze', analyzerResult())
  await page.goto('/')
  await page.getByLabel('Statement to analyze').fill('Mbom')
  await page.getByRole('button', { name: 'Analyze', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Parser result' })).toBeVisible()
  api.reply('POST', '/api/analyzer/analyze', { detail: 'Invalid grammar notation.' }, 422)
  await page.getByRole('button', { name: 'Analyze', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid grammar notation.')
  await expect(page.getByRole('heading', { name: 'Parser result' })).toHaveCount(0)
  await expect(page.getByLabel('Statement to analyze')).toHaveValue('Mbom')
  await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Analysis', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid grammar notation.')
  await expect(page.getByRole('heading', { name: 'No completed analysis' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Token statistics' })).toHaveCount(0)
  expect(api.calls('/api/analyzer/analyze')).toHaveLength(2)
})

test('Analysis separates sentence and Collection frequencies and preserves raw handoffs', async ({ page, api }, testInfo) => {
  const result = tokenAnalysisResult()
  api.reply('POST', '/api/analyzer/analyze', result)
  await page.goto('/#analysis')
  await expect(page.getByRole('heading', { name: 'No completed analysis' })).toBeVisible()
  expect(api.calls('/api/analyzer/analyze')).toHaveLength(0)
  await page.getByRole('link', { name: 'Analyze a sentence' }).click()
  await page.getByLabel('Statement to analyze').fill(result.text)
  await page.getByRole('button', { name: 'Analyze', exact: true }).click()
  await expect(page.getByText('REJECT', { exact: true })).toBeVisible()
  await expect(page.getByRole('table')).toHaveCount(0)
  await page.getByRole('link', { name: 'View detailed analysis' }).click()
  const sentence = page.getByRole('region', { name: 'Analyzed sentence' })
  await expect(sentence.getByText('4 tokens · 2 distinct forms', { exact: true })).toBeVisible()
  await expect(sentence.getByRole('region', { name: 'Observed token frequencies' }).getByRole('row')).toHaveText(['TokenCount', 'veux2', '+2'])
  await expect(sentence.getByRole('region', { name: 'Token category frequencies' }).getByRole('row')).toHaveText(['CategoryCount', 'VERB2', 'UNKNOWN2'])
  await sentence.getByText('Unknown tokens · 1 forms', { exact: true }).click()
  await expect(sentence.getByRole('region', { name: 'Unknown token frequencies' }).getByRole('row')).toHaveText(['TokenCount', '+2'])
  await expect(sentence.getByRole('region', { name: 'Observed orthographic variation candidates' })).toContainText('veux (1) · VEUX (1)')
  await page.screenshot({ path: testInfo.outputPath('token-analysis.png') })
  await page.getByText('Saved Collection - 1 records', { exact: true }).click()
  const corpus = page.getByRole('region', { name: 'Saved Collection results' })
  await expect(corpus.getByText('2 tokens · 1 distinct forms', { exact: true })).toBeVisible()
  await expect(corpus.getByRole('region', { name: 'Observed token frequencies' }).getByRole('row')).toHaveText(['TokenCount', 'taxi2'])
  const tests = corpus.getByRole('region', { name: 'Saved Collection parser results' })
  await tests.getByText('taxi taxi', { exact: true }).click()
  await tests.getByRole('button', { name: 'Use as analyzer input' }).click()
  await expect(page).toHaveURL(/#compiler$/)
  await expect(page.getByLabel('Statement to analyze')).toHaveValue('  taxi taxi\n')
  await expect(page.getByLabel('Statement to analyze')).toBeFocused()
  await expect(page.getByRole('heading', { name: 'Parser result' })).toHaveCount(0)
  expect(api.calls('/api/analyzer/analyze')).toHaveLength(1)
  expect(api.calls('/api/dataset', 'POST')).toHaveLength(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})
