import { randomUUID } from 'node:crypto'
import type { Dataset } from '../../src/types'
import type { TestReport } from '../../src/analyzerTypes'
import { openGrammarSettings } from '../browserGrammar'
import { expect, seedLiveData, test } from './fixtures'
import { analyzePublicInput, origin, protectPublicContext, publicHeaders, readOnlyOwnership } from './publicWorkflows'

test.beforeEach(async ({ context }) => protectPublicContext(context))

test('public visitors analyze immutable tests without accounts while CSRF and read-only boundaries remain enforced', async ({ page }) => {
  await page.goto('/#register')
  await expect(page).toHaveURL(/#compiler$/)
  await expect(page.getByLabel('Statement to analyze')).toBeVisible()
  await expect(page.getByRole('button', { name: /Sign in|Sign out|Create account/i })).toHaveCount(0)
  await expect(page.getByLabel('Registered users')).toHaveCount(0)
  const headers = await publicHeaders(page.request)
  const cookie = (await page.context().cookies()).find((item) => item.name === 'camfranglais_public')
  expect(cookie).toMatchObject({ httpOnly: true, sameSite: 'Lax' })
  expect(await page.evaluate(() => document.cookie)).not.toContain('camfranglais_public')
  const state = await (await page.request.get('/api/analyzer')).json()
  expect(state.grammar_ownership).toEqual(readOnlyOwnership)
  const request = page.waitForRequest((item) => new URL(item.url()).pathname === '/api/analyzer/tests' && item.method() === 'POST')
  const saved = await analyzePublicInput(page, '  taxi\t')
  const submitted = await request
  expect(submitted.headers()['x-csrf-token']).toBe(headers['X-CSRF-Token'])
  expect(submitted.headers().origin).toBe(origin)
  expect(submitted.postDataJSON()).toEqual({ request_id: expect.any(String), text: '  taxi\t', grammar: state.grammar })
  expect(saved.text).toBe('  taxi\t')
  expect(saved.lexical.tokens).toEqual([{ text: 'taxi', category: 'NOUN' }])
  const retry = await page.request.post('/api/analyzer/tests', { headers, data: submitted.postDataJSON() })
  expect(retry.status(), await retry.text()).toBe(200)
  expect(await retry.json()).toEqual(saved)
  expect((await (await page.request.get('/api/analyzer/tests')).json()).summary.total).toBe(1)
  const payload = { request_id: randomUUID(), text: 'taxi', grammar: state.grammar }
  expect((await page.request.post('/api/analyzer/tests', { data: payload })).status()).toBe(403)
  expect((await page.request.post('/api/analyzer/tests', { headers: { Origin: origin }, data: payload })).status()).toBe(403)
  expect((await page.request.post('/api/analyzer/tests', { headers: { ...headers, Origin: 'https://not-this-site.invalid' }, data: payload })).status()).toBe(403)
  const stale = await page.request.post('/api/analyzer/tests', { headers, data: { ...payload, grammar: 'S -> UNKNOWN' } })
  expect(stale.status(), await stale.text()).toBe(409)
  expect((await page.request.put('/api/analyzer/grammar', { headers, data: { grammar: 'S -> UNKNOWN' } })).status()).toBe(403)
  expect((await page.request.post('/api/dataset', { headers, data: { text: 'Cannot create a public entry' } })).status()).toBe(403)
  for (const path of ['/api/auth/session', '/api/auth/login', '/api/workspace/projects', '/api/workspace/history', '/api/coursework', '/api/imports/preview']) {
    expect((await page.request.get(path)).status(), `${path} is not a public endpoint`).toBe(404)
  }
  for (const path of ['/api/analyze', '/api/analyzer/analyze', '/api/readings/lookup']) {
    const data = path.endsWith('lookup') ? { text: 'taxi', language: 'fr' } : { text: 'taxi', ...(path.includes('analyzer') ? { grammar: state.grammar } : {}) }
    expect((await page.request.post(path, { data })).status(), `${path} requires CSRF`).toBe(403)
    const response = await page.request.post(path, { headers, data })
    expect(response.status(), await response.text()).toBe(200)
  }
  expect((await (await page.request.get('/api/dataset')).json()).total).toBe(0)
  expect((await (await page.request.get('/api/analyzer/tests')).json()).summary.total).toBe(1)
  expect(await (await page.request.get(`/api/analyzer/tests/${saved.id}`)).json()).toEqual(saved)
  await page.getByRole('link', { name: 'View detailed analysis', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('group', { name: 'Tests recorded', exact: true })).toContainText('1')
  await page.getByRole('button', { name: 'Inspect test 1', exact: true }).click()
  expect(await page.getByLabel('Analyzed source text').textContent()).toBe('  taxi\t')
  await expect(page.getByRole('button', { name: /Edit test|Delete test/i })).toHaveCount(0)
  await expect(page.getByText(/Creator:/)).toHaveCount(0)
})

test.describe('saved grammar snapshots', () => {
  test.use({ seed: { grammar: 'S -> S NUMBER | NUMBER' } })

  test('saved grammar refresh is explicit and preserves transformations, conflicts, epsilon and original test history', async ({ page }) => {
    await page.goto('/')
    const first = await analyzePublicInput(page, '  123\t')
    expect(first.parse.accepted).toBe(true)
    expect(first.grammar.is_ll1).toBe(true)
    expect(first.metadata.matching_entries).toBe(0)
    await page.getByRole('link', { name: 'View detailed analysis', exact: true }).click()
    await page.getByText('Parser trace for this input', { exact: true }).click()
    await expect(page.getByRole('region', { name: 'Table-driven parser step trace' })).toBeVisible()
    await page.getByText('Saved grammar, transformations & FIRST/FOLLOW', { exact: true }).click()
    await expect(page.getByRole('region', { name: 'Computed FIRST and FOLLOW sets' })).toBeVisible()
    await expect(page.getByText('LL(1) · no table conflicts', { exact: true })).toBeVisible()
    await page.getByText('eliminate direct left recursion', { exact: false }).click()
    await expect(page.getByText(/Replace S -> S alpha/)).toBeVisible()
    await page.getByRole('link', { name: 'Back to Franc Analyzer', exact: true }).click()
    const conflict = 'S -> A NUMBER\nA -> NUMBER | epsilon'
    seedLiveData({ grammar: conflict })
    await page.getByRole('button', { name: 'Analyze', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Reload saved grammar', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Analyze', exact: true })).toBeDisabled()
    await expect(page.getByLabel('Statement to analyze')).toHaveValue('  123\t')
    expect((await (await page.request.get('/api/analyzer/tests')).json()).summary.total).toBe(1)
    await page.getByRole('button', { name: 'Reload saved grammar', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Analyze', exact: true })).toBeEnabled()
    const second = await analyzePublicInput(page, '  123\t')
    expect(second.grammar_source).toBe(conflict)
    expect(second.approval.accepted).toBe(true)
    expect(second.parse.accepted).toBe(false)
    await page.getByRole('link', { name: 'View detailed analysis', exact: true }).click()
    await page.getByText('Saved grammar, transformations & FIRST/FOLLOW', { exact: true }).click()
    await expect(page.getByText('Not LL(1) · inspect conflicts', { exact: true })).toBeVisible()
    await expect(page.getByText('A deterministic LL(1) choice is not available.', { exact: true })).toBeVisible()
    seedLiveData({ grammar: 'S -> epsilon' })
    await openGrammarSettings(page)
    await page.getByRole('button', { name: 'Refresh saved grammar', exact: true }).click()
    await expect(page.getByLabel('Context-free grammar')).toHaveValue('S -> epsilon')
    await expect(page.getByLabel('Context-free grammar')).not.toBeEditable()
    await expect(page.getByRole('button', { name: 'Save grammar', exact: true })).toHaveCount(0)
    const empty = await analyzePublicInput(page, '')
    expect(empty.parse.accepted).toBe(true)
    expect(empty.lexical.tokens).toEqual([])
    await expect(page.getByLabel('Analyzed source text')).toHaveText('(empty input)')
    await page.getByRole('link', { name: 'View detailed analysis', exact: true }).click()
    await page.getByText('Token details for this test', { exact: true }).click()
    await expect(page.getByText('No lexical tokens. The parser will see only $.')).toBeVisible()
    await page.reload()
    await openGrammarSettings(page)
    await expect(page.getByLabel('Context-free grammar')).toHaveValue('S -> epsilon')
    const report: TestReport = await (await page.request.get('/api/analyzer/tests')).json()
    expect(report.summary).toMatchObject({ total: 3, accepted: 3, rejected: 0 })
    expect(report.grammar_summary).toMatchObject({ total: 3, accepted: 2, rejected: 1 })
    expect(report.statistics.total_tokens).toBe(2)
    await page.getByRole('button', { name: 'Inspect test 1', exact: true }).click()
    expect(await page.getByLabel('Analyzed source text').textContent()).toBe('  123\t')
    await page.getByText('Saved grammar, transformations & FIRST/FOLLOW', { exact: true }).click()
    await expect(page.getByRole('region', { name: 'Analyzed sentence or word', exact: true })).toContainText('S -> S NUMBER | NUMBER')
    expect(await (await page.request.get(`/api/analyzer/tests/${first.id}`)).json()).toEqual(first)
    expect((await (await page.request.get('/api/dataset')).json()).total).toBe(0)
  })
})

test.describe('read-only collection provenance and full token analysis', () => {
  const text = '  Le taxi\tdon refuse.\n'
  const meaning = '  Le taxi a refus\u00e9.\n'
  test.use({ seed: {
    grammar: 'S -> FRENCH_FUNCTION_WORD VERB VERB | VERB | NOUN',
    entries: [{ text, french_gloss: meaning, english_gloss: '', entry_type: 'Sentence', language: 'francanglais', contributor: '' }],
  } })

  test('original transcripts remain unchanged while all explicit repeated tests and complete frequencies are retained', async ({ page }) => {
    await page.goto('/#collection')
    const before: Dataset = await (await page.request.get('/api/dataset')).json()
    expect(before.total).toBe(1)
    expect(before.entries[0]).toMatchObject({ text, french_gloss: meaning, review_status: 'unreviewed', ownership: readOnlyOwnership })
    await page.getByRole('button', { name: /^View expression:/ }).click()
    const viewer = page.getByRole('dialog', { name: 'View collection entry', exact: true })
    await expect(viewer.getByLabel('Expression', { exact: true })).toHaveValue(text)
    await expect(viewer.getByLabel('French meaning', { exact: true })).toHaveValue(meaning)
    await expect(viewer.getByLabel('Expression', { exact: true })).not.toBeEditable()
    await viewer.getByRole('button', { name: 'Done', exact: true }).click()
    const collected = await analyzePublicInput(page, text)
    expect(collected.text).toBe(text)
    expect(collected.parse.accepted).toBe(false)
    expect(collected.lexical.statistics.total_tokens).toBe(5)
    expect(collected.metadata.matching_entries).toBe(1)
    expect(collected.metadata.languages).toEqual(['francanglais'])
    const accepted = await analyzePublicInput(page, 'je Veux acheter')
    expect(accepted.lexical.tokens).toEqual([
      { text: 'je', category: 'FRENCH_FUNCTION_WORD' }, { text: 'Veux', category: 'VERB' }, { text: 'acheter', category: 'VERB' },
    ])
    expect(accepted.parse.accepted).toBe(true)
    const word = await analyzePublicInput(page, 'Veux')
    expect(word.lexical.tokens).toEqual([{ text: 'Veux', category: 'VERB' }])
    expect(word.parse.accepted).toBe(true)
    const repeated = await analyzePublicInput(page, 'Veux')
    expect(repeated.id).not.toBe(word.id)
    expect(repeated.text).toBe(word.text)
    const raw = '  Je veux veux, VEUX + + 12\t'
    const frequencies = await analyzePublicInput(page, raw)
    expect(frequencies.text).toBe(raw)
    expect(frequencies.parse.accepted).toBe(false)
    expect(frequencies.lexical.statistics.total_tokens).toBe(8)
    expect(frequencies.lexical.statistics.frequencies).toEqual([
      { token: 'veux', count: 3 }, { token: '+', count: 2 }, { token: 'je', count: 1 }, { token: ',', count: 1 }, { token: '12', count: 1 },
    ])
    await page.getByRole('link', { name: 'View detailed analysis', exact: true }).click()
    const selected = page.getByRole('region', { name: 'Analyzed sentence or word', exact: true })
    expect(await selected.getByLabel('Analyzed source text').textContent()).toBe(raw)
    await selected.getByText('Token details for this test', { exact: true }).click()
    await expect(selected.getByText('8 tokens · 5 distinct forms', { exact: true })).toBeVisible()
    await expect(selected.getByRole('region', { name: 'Observed token frequencies' }).getByRole('row')).toHaveText(['TokenCount', 'veux3', '+2', 'je1', ',1', '121'])
    await expect(selected.getByRole('region', { name: 'Token category frequencies' }).getByRole('row')).toHaveText(['CategoryCount', 'FRENCH_FUNCTION_WORD1', 'VERB3', 'PUNCTUATION1', 'UNKNOWN2', 'NUMBER1'])
    const report: TestReport = await (await page.request.get('/api/analyzer/tests')).json()
    expect(report.summary).toMatchObject({ total: 5, accepted: 4, rejected: 1, acceptance_rate: 80 })
    expect(report.grammar_summary).toMatchObject({ total: 5, accepted: 3, rejected: 2, acceptance_rate: 60 })
    expect(report.statistics.total_tokens).toBe(18)
    expect(report.statistics.frequencies).toContainEqual({ token: 'veux', count: 6 })
    expect(report.statistics.raw_frequencies).toContainEqual({ token: 'Veux', count: 3 })
    expect(report.statistics.raw_frequencies).toContainEqual({ token: 'veux', count: 2 })
    expect(report.statistics.raw_frequencies).toContainEqual({ token: 'VEUX', count: 1 })
    expect(report.unknown_review).toContainEqual({ token: '+', count: 2, tests: 1, forms: ['+'] })
    await expect(page.getByRole('group', { name: 'Tests recorded', exact: true })).toContainText('5')
    await expect(page.getByRole('group', { name: 'Acceptance rate', exact: true })).toContainText('80%')
    await expect(page.getByRole('group', { name: 'Grammar match rate', exact: true })).toContainText('60%')
    expect(await (await page.request.get('/api/dataset')).json()).toEqual(before)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.goBack()
    await expect(page.getByLabel('Statement to analyze')).toHaveValue(raw)
    await expect(page.getByRole('group', { name: 'Vocabulary approval', exact: true })).toContainText('REJECT')
    await page.goForward()
    await expect(page).toHaveTitle('Analysis — Camfranglais Compiler')
    await selected.getByText('Token details for this test', { exact: true }).click()
    await expect(selected.getByText('8 tokens · 5 distinct forms', { exact: true })).toBeVisible()
    await page.reload()
    await expect(page.getByRole('group', { name: 'Tests recorded', exact: true })).toContainText('5')
    await page.getByRole('button', { name: 'Inspect test 5', exact: true }).click()
    expect(await page.getByLabel('Analyzed source text').textContent()).toBe(raw)
    expect(await (await page.request.get('/api/analyzer/tests')).json()).toEqual(report)
    expect(await (await page.request.get('/api/dataset')).json()).toEqual(before)
  })
})
